version: '3'
services:
  orders-service:
    build: .
    ports:
     - "7073:7073"
    environment:
     - MONGODB_ORDERS_SERVICE_HOST=mongo-db
     - SC_HOST=sc-host
  mongo-db:
    image: mongo:latest
    ports:
     - "27017:27017"
  sc-host:
    image: servicecomb/service-center:latest
    ports:
     - "30100:30100"
